[pytest]
addopts = -p no:faulthandler --maxfail=2 --disable-warnings -v --html=reports/reports.html --selfcontained-html --show-capture='stdout' --tb=native
python_files = test_*.py
python_functions = test_*
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

filterwarnings =
    error
    ignore::UserWarning
    ignore::DeprecationWarning


# addopts - add options
# -p no:faulthandler - FaultHandler is used for diagnosing crashes, debugs. (May be useful in developing and Testing)
# --html:reports/reports.html - Reports folder. 
# --selfcontained-html:  By default, pytest-html creates an HTML file along with an external CSS stylesheet and separate asset folders for styling and icons.
#                        When you pass --self-contained-html, it forces pytest-html to embed all CSS styles, JavaScript, and assets inline directly into a single HTML file using data URIs.
# --show-capture='stdout': Only show captured stdout in the failure traceback summaries.
# --tb=native  : By default, Pytest formats Python exception tracebacks with color-coded, detailed line-by-line context (showing local variables, exact failing code blocks, etc.).
#                Setting --tb=native forces Pytest to use Python’s standard library traceback format instead.
# Python Test Files will be - test_*.py
# Python Test Functions will be  - test_*
# log_cli = true : Enable live logging to the console
# log_cli_level = INFO :  Set the minimum log level to display (e.g., INFO, DEBUG, WARNING)
# log_cli_format = %(asctime)s [%(levelname)s] %(message)s -Format how logs appear in the terminal
# log_cli_date_format = %Y-%m-%d %H:%M:%S  - Format the timestamp display
# filterwarnings = error: Turns all unhandled Python warnings into hard errors, causing tests that trigger them to fail.
#                  ignore::UserWarning: Overrides the error rule specifically for UserWarning instances, preventing them from failing your tests.
#                  ignore::DeprecationWarning: Overrides the error rule for DeprecationWarning instances (often raised by third-party packages using older features).





