name: Regression Suite
on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '30 2 * * *' # Runs at 02:30

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2 # Upgraded from v3

      - name: Setup Python
        uses: actions/setup-python@v5.4.0 # Upgraded from v3
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel packaging
          pip install -r requirements.txt

      - name: run tests
        run: |
          # Added flags to actually generate the HTML report file
          python -m pytest -s --html=report.html --self-contained-html

      - name: upload report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/
